export function getStarterBooks() {
  return [
    {
      title: "Dune",
      author: "Frank Herbert",
      genre: "Sci-Fi",
      publication_year: 1965,
      source: "Goodreads",
      source_url: "https://www.goodreads.com/book/show/44767458-dune",
      synopsis: "A desert planet, a political dynasty, and a mythic ecological future.",
      review: "A dense but rewarding cornerstone of speculative fiction.",
      rating: 5,
      cover_url: null,
    },
    {
      title: "1984",
      author: "George Orwell",
      genre: "Dystopian",
      publication_year: 1949,
      source: "Open Library",
      source_url: "https://openlibrary.org/works/OL1168083W/Nineteen_Eighty-Four",
      synopsis: "A stark surveillance-state novel about language, memory, and control.",
      review: "Still sharp and unsettling.",
      rating: 4,
      cover_url: null,
    },
    {
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      genre: "Fantasy",
      publication_year: 1937,
      source: "Barnes & Noble",
      source_url: "https://www.barnesandnoble.com/w/the-hobbit-j-r-r-tolkien/1100068700",
      synopsis: "A home-loving hobbit is pulled into a quest of treasure, courage, and consequence.",
      review: "Warm, adventurous, and foundational.",
      rating: 5,
      cover_url: null,
    },
  ];
}
